language: bash

env:
  - ROWAN_PROJECTS_HOME="$TRAVIS_BUILD_DIR/travis_tests" ST_LAUNCHER_HOME="$TRAVIS_BUILD_DIR/home"

before_script:
    - curl -L "https://github.com/kward/shunit2/archive/v2.1.7.tar.gz" | tar zx -C $TRAVIS_BUILD_DIR/travis_tests
    - git clone https://github.com/GemTalk/Rowan.git travis_tests/Rowan
    - curl  -O -s -S "https://downloads.gemtalksystems.com/pub/GemStone64/3.5.0/GemStone64Bit3.5.0-x86_64.Linux.zip"
    - mkdir $ST_LAUNCHER_HOME/platforms/gemstone
    - mkdir $ST_LAUNCHER_HOME/platforms/gemstone/products
    - unzip -q -d "$ST_LAUNCHER_HOME/platforms/gemstone/products" GemStone64Bit3.5.0-x86_64.Linux.zip

script:
- bash travis_tests/st_launcher_tests.sh
