language: bash

env:
  - ROWAN_PROJECTS_HOME="$TRAVIS_BUILD_DIR"

before_script:
    - curl -L "https://github.com/kward/shunit2/archive/v2.1.7.tar.gz" | tar zx -C $TRAVIS_BUILD_DIR/travis_tests
    - git clone https://github.com/GemTalk/Rowan.git travis_tests/Rowan
    - ls -altr travis_tests

script:
- bash travis_tests/st_launcher_tests.sh
