language: bash
sudo: true

env:
  - ROWAN_PROJECTS_HOME="$TRAVIS_BUILD_DIR/travis_tests" ST_LAUNCHER_HOME="$TRAVIS_BUILD_DIR/home" SHUNIT_COLOR='always' TRAVIS_SUDO=sudo

before_script:
    - bin/install.sh 
    - ls -altr
    - ls -altr bin
    - ls -altr home/images/admin_gs_350/snapshots
    - ls -altr home/platforms/gemstone/downloads
    - ls -altr home/platforms/gemstone/products
    - ls -altr travis_tests
    - sudo ls -altr $HOME/.st_launcher
    - ls -altr /usr/local/bin/smalltalk/gemstone

script:
- bash travis_tests/st_launcher_tests.sh
