language: bash
sudo: true

env:
  - INSTALL_SCRIPT="bin/install.sh" ROWAN_PROJECTS_HOME="$TRAVIS_BUILD_DIR/travis_tests" ST_LAUNCHER_HOME="$TRAVIS_BUILD_DIR/home" SHUNIT_COLOR='always' TRAVIS_SUDO=sudo

before_script:
    - $INSTALL_SCRIPT 
    - ls -altr
    - ls -altr home/images/admin_gs_350/snapshots
    - ls -altr home/platforms/gemstone/downloads
    - ls -altr home/platforms/gemstone/products
    - ls -altr home/images/admin_pharo_70
    - ls -altr home/platforms/pharo/products
    - ls -altr home/platforms/pharo/products/*
    - ls -altr travis_tests
    - ls -altr $HOME
    - ls -altr $HOME/.st_launcher
    - ls -altr /usr/local/bin/smalltalk/gemstone

script:
- bash travis_tests/st_launcher_tests.sh
