language: bash

before_script:
    - curl -L "https://github.com/kward/shunit2/archive/v2.1.7.tar.gz" | tar zx
    - ls -altr .
    - ls -altr shunit2-2.1.7/
    - ls -altrd shunit2-2.1.7/*
    - ls -altr shunit2-2.1.7/sunit

script:
- bash travis_tests/sample_script_tests.sh
