language: bash
sudo: true

env:
  - ROWAN_PROJECTS_HOME="$TRAVIS_BUILD_DIR/travis_tests" ST_LAUNCHER_HOME="$TRAVIS_BUILD_DIR/home" SHUNIT_COLOR='always' TRAVIS_SUDO=sudo

before_script:
    - bin/install.sh 

script:
- bash travis_tests/st_launcher_tests.sh
