#!/usr/bin/env bash
#
# Args:
# 	<stash-file-path> [ [<image-name> [ <vm-args> ] ] -- ] [ <script-args> ]
#

. $HOME/.st_launcher/st_launcher_default.env

stashFile=`realpath $1`
shift
imageName=""
vmArgs=""
scriptArgs=""
debugCommandError="false"

interpArgs="$*"

if [ "$ST_LAUNCHER_DEFAULT_PLATFORM" = "gemstone" ] ; then
	inputFile=`mktemp`
	cat - > $inputFile << EOF

	iferr 1 stk

	set user SystemUser
	set password swordfish

	set solologin on
	login

	run
	StLauncherPlatform generateVmScriptLaunchCommandLineFrom: '$interpArgs'
%
exit 
EOF
	export GEMSTONE="$ST_LAUNCHER_DEFAULT_PRODUCT_PATH"
	scriptCmdLine=`$GEMSTONE/bin/topaz -lq -C "GEM_SOLO_EXTENT=$ST_LAUNCHER_DEFAULT_SNAPSHOT_PATH" -S $inputFile`
elif [ "$ST_LAUNCHER_DEFAULT_PLATFORM" = "pharo" ] ; then
	echo "PHARO not supported ... yet"
	exit 1
else
	echo "\$ST_LAUNCHER_DEFAULT_PLATFORM not defined"
	exit 1
fi

file=`mktemp`
cat - > $file << EOF
	iferr 1 stk

	$solo
	login

	run
	[
		StashScript
			loadAndExecuteScriptClassFile: '$stashFile'
			stashArgs: '$scriptArgs'
			topazArgs: '$vmArgs'
			workingDir: '$pwd'
			projectName: '__EXECUTE_STASH_SCRIPT_PROJECT__'
			packageName: '__EXECUTE_STASH_SCRIPT_PACKAGE__'
			symDictName: '_EXECUTE_STASH_SCRIPT_SymbolDict__' ]
		on: StashCommandError
		do: [:ex |
			$debugCommandError
				ifTrue: [ ex pass ]
				ifFalse: [ 
					StashScript 
						ansiRedOn: GsFile stdout 
						during: [ GsFile stdout nextPutAll: ex description ].
					GsFile stdout lf	] ]
%
EOF

$scriptCmdLine -S $file
